version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  test-runner:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: test-runner
    platform: linux/amd64
    entrypoint: [ "/bin/bash", "./docker/wait-for-grid.sh" ]
    command: [ "/bin/bash", "./docker/pytest.sh" ]
    depends_on:
      - selenium-hub
      - chrome
    tty: true
