name: Pytest with slack app

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'  

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run pytest
      run: |
        echo "Tags: ${{ github.event.inputs.tags }}" 
        docker-compose -f ./docker_with_slack/docker/docker-compose.yaml config
        docker-compose -f ./docker_with_slack/docker/docker-compose.yaml up \
        --abort-on-container-exit \
        --exit-code-from test-runner

    - name: Extract test results
      run: |
        docker cp test-runner:/app/report.html .
      if: always()

    - name: Send test report to Slack
      run: |
        curl -F file=@report.html -F "initial_comment=Test Report" -F channels=C02NNKV205R -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" https://slack.com/api/files.upload
      if: always()
