name: pytest workflow

on:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        brew update
        brew install allure

    - name: Run pytest
      run: |
        docker-compose -f ./docker/docker-compose.yaml config
        docker-compose -f ./docker/docker-compose.yaml up \
        --abort-on-container-exit \
        --exit-code-from test-runner
        
    - name: Extract test results
      run: |
        docker cp test-runner:/app/output .
        
    - name: Generate reports 
      run: |
        allure generate output/
        
    - name: Publishing Allure artipacts
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
